### ISSUE TITLE
Permissions for default app pool account

### ISSUE THREAD

**Issue by jaredfholgate** [Microsoft/aspnet-docker#33]
Hi

When running an existing ASP.NET MVC app in this application I got the error;

> CS0016: Could not write to output file 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\********\********\*************.dll' -- 'The directory name is invalid. '

It turns out the app pool account is missing some permissions for temp files. I've not pin pointed which files yet, but a work around is to add this PowerShell to the Dockerfile;

`Add-LocalGroupMember -Group 'Administrators' -Member 'IIS AppPool\DefaultAppPool';`

This is obviously not an ideal solution and it would be good to identify exactly which folders this account requires access to.

I'm running via the Visual Studio debugger and I got the image for the first time on Friday 16th June.

This issue could be very frustrating for anyone expecting this to work out of the box and it has affected at least one other person.

See this Stack Overflow question for further details;

[https://stackoverflow.com/questions/44605735/starting-a-barebones-mvc-c-sharp-asp-net-project-in-docker-gives-compilation-er/44634199](https://stackoverflow.com/questions/44605735/starting-a-barebones-mvc-c-sharp-asp-net-project-in-docker-gives-compilation-er/44634199)

Thanks

Jared

**Comment by pbering** [comment]
Same issue here...: only workaround that I have found is to use the previous image `microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.1198`

**Comment by davideicardi** [comment]
Another workaround is to work on a different website. In my docker file I remove the default website and add a new one.


    RUN New-Item c:\webapp -type directory
    RUN Remove-WebSite -Name 'Default Web Site' 
    RUN New-Website -Name 'webapp' -Port 80 -PhysicalPath 'c:\webapp' -ApplicationPool '.NET v4.5'

**Comment by HongGit** [comment]
This is a known issue because ServiceMonitor has a different user profile from ApplicationPoolIdentity.  We are working on a fix, and will release an update.

Simple workaround is as @jaredfholgate suggests, change identity of the DefaultAppPool to Administrator or System.

**Comment by shirhatti** [comment]
This has been fixed as of the 10.0.14393.1480 (July) updates

**Comment by MarekLani** [comment]
I am still getting the error. Sample WebApp ASP.NET added docker support. Works when runninng from Visual Studio when trying to run image directly thru docker I get over mentioned erorrs

**Comment by MichaelSimons** [comment]
@andras-ferencz - I apologize for the frustration you are experiencing.  I do want to remind everyone to be respectful as stated in the [Microsoft  Code of Conduct](https://microsoft.github.io/codeofconduct/).

If you can provide the details of the issue you are encountering perhaps @HongGit and @shirhatti can help resolve the issue.

**Comment by HongGit** [comment]
@andras-ferencz and @MarekLani could you please share the Visual Studio version you are using or if you could find out the version of the base ASP.NET docker you are using?  That will help us to investigate the issue.

IIS team has recently released a new version of Service Monitor (https://github.com/Microsoft/iis-docker/commit/af495067e62da437ec16adcade2dcd80a316384f#diff-01a019af0d92d881ba54fea93328a9f3), please try out the new version and see if it resolves the issue.

**Comment by tfenster** [comment]
@HongGit I see the same error using base image microsoft/aspnet:4.7.2-windowsservercore-ltsc2016. Inspect shows the following
```
"Created": "2018-06-13T22:48:22.6847957Z"
```
The Add-LocalGroupMember workaround fixed it for me

**Comment by fitims** [comment]
@Jared

You saved my life ! I tried everything under the sun to have AppPool use different identiy, but unsuccessful. You tip worked like a charm. Thanks !!!
